### ISSUE TITLE
Pull request template with checklist

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-javascript#170]
I think it would be helpful to have a PR template for the tree-sitter-* grammar repos that would list the things we care about when reviewing a pull request. I started [document with contribution guidelines and tips](https://github.com/returntocorp/tree-sitter-guidelines), which among other things contains such a list. Here's a proposed PR template:

```markdown
Checklist:
- [ ] All tests pass in CI.
- [ ] There are sufficient tests for the new fix/feature.
- [ ] Grammar rules have not been renamed unless absolutely necessary.
- [ ] The conflicts section hasn't grown too much.
- [ ] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).
```

which is rendered as:

Checklist:
- [ ] All tests pass in CI.
- [ ] There are sufficient tests for the new fix/feature.
- [ ] Grammar rules have not been renamed unless absolutely necessary.
- [ ] The conflicts section hasn't grown too much.
- [ ] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

Ideally the template would be set at the tree-sitter organization level so that we have to maintain it in only one place (but it doesn't seem to be supported; the closest I could find is [this](https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/)).

I think I'll make a PR for adding the PR template. Hang on.

**Comment by dcreager** [comment]
Great idea, @mjambon, thanks for putting this together!
